#!/bin/sh
ulimit -c 2000

host=vm-pear-103

if test "$1" = "o"
then
    ./mnhtesto -P9000 -C1024 2>&1 | tee out-o

elif test "$1" = "c"
then
    ./mnhtestc \
        -u https://$host:8443/ \
        -u https://$host:8443/qwe02 \
        -u https://$host:8443/qwe03 \
        -u https://$host:8443/qwe04 \
        -u https://$host:8443/qwe05 \
        -u https://$host:8443/qwe06 \
        -u https://$host:8443/qwe07 \
        -u https://$host:8443/qwe08 \
        -u https://$host:8443/qwe09 \
        -u https://$host:8443/qwe0a \
        -u https://$host:8443/qwe0b \
        -Q qwe:1kb/5sec \
        -Q asd:1mb/5sec \
        -p1000 -A 2>&1 | tee out-c

else
    echo 'Invalid arguments'
    exit 1
fi
