#!/bin/sh
ulimit -c 2000

host=vm-pear-103
host=mndo-01.mooo.com
proxy=localhost
delay=4500
parallel=1
quota=xcv

if test "$1" = "o"
then
    ./mnhtesto                         \
        -Q qwe:1kb/5sec                \
        -Q asd:1mb/5sec                \
        -Q zxc:150req/15sec            \
        -Q xcv:1req/5sec               \
        -Q xcv00:80req/5sec            \
        -Q xcv01:80req/5sec:1:h        \
        -Q cvb00:80req/5sec:0.5:h      \
        -P 9000 -C 1024 2>&1 | tee out-o

elif test "$1" = "c"
then
    ./mnhtestc                         \
        -u https://$host:8443/         \
        -u https://$host:8443/qwe02    \
        -u https://$host:8443/qwe03    \
        -u https://$host:8443/qwe04    \
        -u https://$host:8443/qwe05    \
        -u https://$host:8443/qwe06    \
        -u https://$host:8443/qwe07    \
        -u https://$host:8443/qwe08    \
        -u https://$host:8443/qwe09    \
        -u https://$host:8443/qwe0a    \
        -u https://$host:8443/qwe0b    \
        -p $parallel -A 2>&1 | tee out-c

elif test "$1" = "c1"
then
    ./mnhtestc -u https://$host:8443/ -Q $quota -z $delay

elif test "$1" = "c2"
then
    ./mnhtestc -P $proxy -u https://$host:8443/ -Q $quota -S X-CL-RL -z $delay

else
    echo 'Invalid arguments'
    exit 1
fi
