#!/bin/sh
#ulimit -c 2000

host=mndo-01.mooo.com
#proxy=10.1.3.103
proxy=localhost
delay=1000
parallel=1
quota=xcv

command=$1
shift

if test "$command" = "o"
then
    ./mnhtesto                         \
        -Q qwe:1kb/5sec                \
        -Q asd:1mb/5sec                \
        -Q zxc:150req/15sec            \
        -Q xcv:1req/5sec               \
        -Q xcv00:80req/5sec            \
        -Q xcv01:80req/5sec:1:h        \
        -Q cvb00:80req/5sec:0.5:h      \
        -P 9000 -C 1024 2>&1 | tee out-o

elif test "$command" = "c"
then
    ./mnhtestc                         \
        -u https://$host:8443/         \
        -u https://$host:8443/qwe02    \
        -u https://$host:8443/qwe03    \
        -u https://$host:8443/qwe04    \
        -u https://$host:8443/qwe05    \
        -u https://$host:8443/qwe06    \
        -u https://$host:8443/qwe07    \
        -u https://$host:8443/qwe08    \
        -u https://$host:8443/qwe09    \
        -u https://$host:8443/qwe0a    \
        -u https://$host:8443/qwe0b    \
        -p $parallel -A 2>&1 | tee out-c

elif test "$command" = "c0"
then
    #valgrind --suppressions=out.0 ./mnhtestc -u https://$host:8443/ -z $delay $@
    #valgrind --leak-check=full --track-origins=yes --suppressions=out.0 ./mnhtestc -u https://$host:8443/ -z $delay $@
    #valgrind --leak-check=full --track-origins=yes --gen-suppressions=all ./mnhtestc -u https://$host:8443/ -z $delay $@
    #valgrind --gen-suppressions=all ./mnhtestc --help
    #valgrind --leak-check=full --track-origins=yes ./mnhtestc -u https://$host:8443/ -z $delay $@
    ./mnhtestc -u https://$host:8443/ -z $delay $@

elif test "$command" = "c1"
then
    ./mnhtestc -p $parallel -u https://$host:8443/ -z $delay $@

elif test "$command" = "c2"
then
    ./mnhtestc -A -p $parallel -u https://$host:8443/ -z $delay $@

elif test "$command" = "c10"
then
    ./mnhtestc -P $proxy -u http://$host:8080/ -z $delay $@

elif test "$command" = "c11"
then
    ./mnhtestc -p $parallel -P $proxy -u http://$host:8080/ -z $delay $@

elif test "$command" = "c12"
then
    ./mnhtestc -A -p $parallel -P $proxy -u http://$host:8080/ -z $delay $@

elif test "$command" = "c13"
then
    ./mnhtestc -P $proxy -u http://$host:8080/ -Q $quota -S X-CL-RL -z $delay $@


elif test "$command" = "c20"
then
    ./mnhtestc -P $proxy -u http://$host:8080/ -Q @quotas-qwe -S X-CL-RL -z $delay $@

elif test "$command" = "c21"
then
    ./mnhtestc -A -p $parallel -P $proxy -u http://$host:8080/ -Q @quotas-qwe -S X-CL-RL -z $delay $@

elif test "$command" = "c22"
then
    ./mnhtestc -p $parallel -P $proxy -u http://$host:8080/ -Q @quotas-qwe -S X-CL-RL -z $delay $@

elif test "$command" = "c30"
then
    ./mnhtestc -u http://$proxy:8080/$host/qwe02 -Q @quotas-qwe -S X-CL-RL -z $delay $@

else
    echo 'Invalid arguments'
    exit 1
fi
